[build]
  # Directory where your build files are located (update this if your output folder is different)
  publish = "build"
  # Command to build your project
  command = "npm run build"

# Settings for redirects (optional, but useful for SPA apps to handle routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional settings for different contexts (e.g., production, preview, branch deploys)
# [context.production]
#   command = "npm run build:prod"
